---
title: "Multivariante"
author: "Oscar Gerardo Hernández Martínez"
date: "2/9/2019"
output: pdf_document
---

# Datos multidimensionales

## Ejemplo con tres dimensiones

```{r}
ans = sample(c("Sí", "No"), size = 100, replace = T)
sex = sample(c("H", "M"), size = 100, replace = T)
place = sample(c("San Francisco", "Barcelona", "Valencia", 
                "Cobija", "Asturias"), size = 100, replace = T)
table(sex, ans, place)
ftable(sex, ans, place)
ftable(sex, ans, place, col.vars = c("sex", "ans"))
```

### Filtrar las tablas

```{r}
table(sex, ans, place)["M", "Sí", "San Francisco"]
table(sex, ans, place)[ , "Sí", "Valencia"]
table(sex, ans, place)[ ,"No", ]
table(sex, ans, place)["M", , "Cobija"]
```

### Frecuencias relativas

```{r}
prop.table(table(sex, ans, place)) #Frec. Rel. Globales
prop.table(table(sex, ans, place), margin = 3) #Frec. Rel. Marg. X Lugar
prop.table(table(sex, ans, place), margin = c(1,3)) 
#Frec. Rel. Marg. X Sexo y Lugar

ftable(prop.table(table(sex, ans, place)))
```

### People (Hair-Eye-Color)

```{r}
HairEyeColor

sum(HairEyeColor) -> total
```

El total de individuos de la taba de datos `r total`.

```{r}
prop.table(HairEyeColor, margin = 3) #Frec. Rel. X Sexo
```


```{r}
prop.table(HairEyeColor, margin = c(1,2)) #Frec. Rel. X Color Cabello y Ojos
```

```{r}
aperm(HairEyeColor, perm = c("Sex", "Hair", "Eye"))
```

```{r}
library(kableExtra)
kable(HairEyeColor)
```


```{r, results='asis'}
library(xtable)
sex = factor(c("H", "M", "M", "M", "H", "H", "M", "M"))
answer = factor(c(sample(c("S", "N"), size = length(sex), replace = T)))
#Es necesario colocar en {r} el parámetro results = 'asis'
#Para que no se muestre el código en LaTeX sin procesar
#La función xtable solo es útil con tablas bidimensionales.
xtable(table(sex, answer))
```

